using UnityEngine;

namespace WorldGeneration
{
    /// <summary>
    /// Generates terrain height data using layered Perlin noise combined with
    /// a Voronoi-based island mask for creating isolated landmasses.
    /// </summary>
    public class NoiseGenerator : MonoBehaviour
    {
        [Header("World Settings")]
        [Tooltip("Reproducible generation seed. Change to get different worlds.")]
        [SerializeField] private int worldSeed = 42;
        [Tooltip("Sea level baseline (0-1). Controls where water sits relative to normalized noise.")]
        [SerializeField] private float seaLevel = 0.25f;

        [Header("Height Noise Settings")]
        [Tooltip("Number of noise octaves (layers). More = more detail, slower. 4-6 recommended.")]
        [SerializeField] private int octaves = 6;
        [Tooltip("Base noise frequency. Higher = smaller features. Typical 0.005-0.05.")]
        [SerializeField] private float baseFrequency = 0.02f;
        [Tooltip("Amplitude falloff per octave (0-1). Lower = rougher terrain. ~0.4-0.6 recommended.")]
        [SerializeField] private float persistence = 0.5f; // Amplitude multiplier per octave
        [Tooltip("Frequency multiplier per octave (>1). Higher = more high-frequency detail.")]
        [SerializeField] private float lacunarity = 2.0f;  // Frequency multiplier per octave
        [Tooltip("Vertical scale of terrain in world units. Increase to make mountains taller.")]
        [SerializeField] private float heightMultiplier = 50f;

        [Header("Island Mask Settings")]
        [Tooltip("Large-scale shape noise frequency used to vary island outlines. Higher = more fractal detail.")]
        [SerializeField] private float islandFrequency = 0.005f;
        [Tooltip("Island mask threshold. Higher value -> fewer/smaller islands. Tune 0.3-0.7.")]
        [SerializeField] private float islandThreshold = 0.6f; // Higher = fewer islands
        [Tooltip("Controls how quickly island mask falls off at edges. Larger = sharper edges.")]
        [SerializeField] private float islandFalloffStrength = 1.5f;
        [Tooltip("(Not currently used directly) Suggested min/max island feature sizes in world units.")]
        [SerializeField] private Vector2 islandSizeRange = new Vector2(50f, 200f);

        [Header("Voronoi Settings")]
        [Tooltip("Voronoi cell scale. Smaller = more cells (many small islands), larger = fewer/larger cells.")]
        [SerializeField] private float voronoiScale = 0.03f;
        [Tooltip("(Reserved) Number of voronoi cells used for distribution hashing.")]
        [SerializeField] private int voronoiCellCount = 10;

        [Header("Debug")]
        [Tooltip("Size of debug textures generated by Generate Debug Textures (Play Mode).")]
        [SerializeField] private int debugTextureSize = 256;
        [SerializeField] [HideInInspector] public Texture2D debugHeightTexture;
        [SerializeField] [HideInInspector] public Texture2D debugMaskTexture;

        // Cached offsets for octaves (generated from seed)
        private Vector2[] octaveOffsets;
        private System.Random prng;

        private void Awake()
        {
            Initialize(worldSeed);
        }

        /// <summary>
        /// Initialize the noise generator with a specific seed.
        /// </summary>
        public void Initialize(int seed)
        {
            worldSeed = seed;
            prng = new System.Random(seed);
            
            // Generate random offsets for each octave
            octaveOffsets = new Vector2[octaves];
            for (int i = 0; i < octaves; i++)
            {
                float offsetX = prng.Next(-100000, 100000);
                float offsetZ = prng.Next(-100000, 100000);
                octaveOffsets[i] = new Vector2(offsetX, offsetZ);
            }
        }

        /// <summary>
        /// Get the terrain height at a world position.
        /// Returns terrain height including underwater slopes near shorelines.
        /// </summary>
        public float GetHeight(float x, float z)
        {
            float islandMask = GetIslandMask(x, z);
            
            // islandMask is now in range [-1, 1]
            // Negative = underwater near shore, 0 = shoreline, positive = land
            
            float baseHeight = GetLayeredPerlinNoise(x, z);
            
            // For land (mask > 0): normal terrain with height variation
            // For underwater (mask <= 0): slope down from shoreline
            float maskedHeight;
            if (islandMask > 0)
            {
                maskedHeight = baseHeight * islandMask;
            }
            else
            {
                // Underwater slope: use mask directly (negative) to create downward slope
                // This gives us terrain that goes from 0 at shore to negative underwater
                maskedHeight = seaLevel + islandMask * 0.3f; // Gradual underwater slope
            }
            
            // Subtract sea level and apply height multiplier
            float finalHeight = (maskedHeight - seaLevel) * heightMultiplier;

            return finalHeight;
        }

        /// <summary>
        /// Check if a position is land (above sea level).
        /// </summary>
        public bool IsLand(float x, float z)
        {
            return GetHeight(x, z) > 0f;
        }

        /// <summary>
        /// Get raw height value without island masking (useful for debugging).
        /// </summary>
        public float GetRawHeight(float x, float z)
        {
            return GetLayeredPerlinNoise(x, z);
        }

        /// <summary>
        /// Get the island mask value at a position.
        /// Returns -1 to 1 range: negative = underwater slope, 0 = shoreline, positive = land.
        /// </summary>
        public float GetIslandMask(float x, float z)
        {
            // Get Voronoi-based cellular noise for island distribution
            float voronoiValue = GetVoronoiNoise(x, z);
            
            // Additional large-scale noise to vary island shapes
            float shapeNoise = Mathf.PerlinNoise(
                x * islandFrequency + 1000f,
                z * islandFrequency + 1000f
            );

            // Combine Voronoi with shape noise
            float combinedMask = voronoiValue * shapeNoise;

            // Apply threshold - but allow negative values for underwater slopes
            float thresholdedMask = combinedMask - islandThreshold;
            
            // Normalize so that threshold boundary = 0, above = positive land, below = negative underwater
            // This creates a smooth transition across the shoreline
            float normalizedMask = thresholdedMask / (1f - islandThreshold);
            
            // Apply falloff only to positive (land) portion
            if (normalizedMask > 0)
            {
                return Mathf.Pow(normalizedMask, islandFalloffStrength);
            }
            else
            {
                // Underwater: allow gradual slope down (clamped to prevent infinite depth)
                return Mathf.Max(-1f, normalizedMask);
            }
        }

        /// <summary>
        /// Generate layered Perlin noise using multiple octaves.
        /// </summary>
        private float GetLayeredPerlinNoise(float x, float z)
        {
            if (octaveOffsets == null || octaveOffsets.Length != octaves)
            {
                Initialize(worldSeed);
            }

            float amplitude = 1f;
            float frequency = baseFrequency;
            float noiseValue = 0f;
            float maxPossibleValue = 0f;

            for (int i = 0; i < octaves; i++)
            {
                float sampleX = x * frequency + octaveOffsets[i].x;
                float sampleZ = z * frequency + octaveOffsets[i].y;

                // Perlin noise returns 0-1, shift to -1 to 1 for better layering
                float perlinValue = Mathf.PerlinNoise(sampleX, sampleZ) * 2f - 1f;
                
                noiseValue += perlinValue * amplitude;
                maxPossibleValue += amplitude;

                amplitude *= persistence;
                frequency *= lacunarity;
            }

            // Normalize to 0-1 range
            noiseValue = (noiseValue / maxPossibleValue + 1f) / 2f;
            
            return noiseValue;
        }

        /// <summary>
        /// Generate Voronoi (cellular) noise for island distribution.
        /// Returns higher values near cell centers, lower values near edges.
        /// </summary>
        private float GetVoronoiNoise(float x, float z)
        {
            float scaledX = x * voronoiScale;
            float scaledZ = z * voronoiScale;

            // Get the cell coordinates
            int cellX = Mathf.FloorToInt(scaledX);
            int cellZ = Mathf.FloorToInt(scaledZ);

            float minDistToCenter = float.MaxValue;
            float secondMinDist = float.MaxValue;

            // Check surrounding cells (3x3 grid)
            for (int offsetX = -1; offsetX <= 1; offsetX++)
            {
                for (int offsetZ = -1; offsetZ <= 1; offsetZ++)
                {
                    int neighborX = cellX + offsetX;
                    int neighborZ = cellZ + offsetZ;

                    // Get deterministic random point within cell
                    Vector2 cellCenter = GetCellCenter(neighborX, neighborZ);

                    // Distance from sample point to cell center
                    float distX = scaledX - cellCenter.x;
                    float distZ = scaledZ - cellCenter.y;
                    float dist = Mathf.Sqrt(distX * distX + distZ * distZ);

                    if (dist < minDistToCenter)
                    {
                        secondMinDist = minDistToCenter;
                        minDistToCenter = dist;
                    }
                    else if (dist < secondMinDist)
                    {
                        secondMinDist = dist;
                    }
                }
            }

            // Return inverted distance (1 at center, 0 at edges)
            // Using difference between closest and second closest for better edges
            float edgeDist = secondMinDist - minDistToCenter;
            return Mathf.Clamp01(edgeDist * 2f);
        }

        /// <summary>
        /// Get deterministic random center point for a Voronoi cell.
        /// </summary>
        private Vector2 GetCellCenter(int cellX, int cellZ)
        {
            // Use cell coordinates to seed random position. Include voronoiCellCount
            // in the hash to make the field purposeful and avoid unused field warnings.
            int hash = Hash2D(cellX, cellZ) ^ voronoiCellCount;
            System.Random cellRng = new System.Random(hash + worldSeed);

            float randX = (float)cellRng.NextDouble();
            float randZ = (float)cellRng.NextDouble();

            return new Vector2(cellX + randX, cellZ + randZ);
        }

        /// <summary>
        /// Simple 2D hash function for deterministic randomness.
        /// </summary>
        private int Hash2D(int x, int z)
        {
            int hash = x * 374761393 + z * 668265263;
            hash = (hash ^ (hash >> 13)) * 1274126177;
            return hash;
        }

        /// <summary>
        /// Get the normalized height (0-1) at a position, useful for biome calculations.
        /// </summary>
        public float GetNormalizedHeight(float x, float z)
        {
            float height = GetHeight(x, z);
            return Mathf.Clamp01(height / heightMultiplier);
        }

        /// <summary>
        /// Get the slope at a position (0-1 where 1 is vertical).
        /// </summary>
        public float GetSlope(float x, float z, float sampleDistance = 1f)
        {
            float heightCenter = GetHeight(x, z);
            float heightLeft = GetHeight(x - sampleDistance, z);
            float heightRight = GetHeight(x + sampleDistance, z);
            float heightUp = GetHeight(x, z + sampleDistance);
            float heightDown = GetHeight(x, z - sampleDistance);

            float slopeX = Mathf.Abs(heightRight - heightLeft) / (2f * sampleDistance);
            float slopeZ = Mathf.Abs(heightUp - heightDown) / (2f * sampleDistance);

            // Convert to angle and normalize (assuming max slope of 45 degrees = 1)
            float maxSlope = Mathf.Max(slopeX, slopeZ);
            return Mathf.Clamp01(maxSlope);
        }

        /// <summary>
        /// Generate runtime debug textures for raw normalized height and island mask.
        /// Call this from the inspector (Context Menu) while in Play Mode.
        /// </summary>
        [ContextMenu("Generate Debug Textures")]
        public void GenerateDebugTextures()
        {
            int size = Mathf.Max(8, debugTextureSize);

            if (debugHeightTexture == null || debugHeightTexture.width != size || debugHeightTexture.height != size)
            {
                debugHeightTexture = new Texture2D(size, size, TextureFormat.RGBA32, false);
                debugHeightTexture.wrapMode = TextureWrapMode.Clamp;
            }

            if (debugMaskTexture == null || debugMaskTexture.width != size || debugMaskTexture.height != size)
            {
                debugMaskTexture = new Texture2D(size, size, TextureFormat.RGBA32, false);
                debugMaskTexture.wrapMode = TextureWrapMode.Clamp;
            }

            float worldRange = size; // samples in [-worldRange, worldRange]

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float nx = x / (float)(size - 1);
                    float ny = y / (float)(size - 1);

                    float worldX = (nx * 2f - 1f) * worldRange;
                    float worldZ = (ny * 2f - 1f) * worldRange;

                    float raw = GetLayeredPerlinNoise(worldX, worldZ);
                    float mask = GetIslandMask(worldX, worldZ);

                    float rawClamped = Mathf.Clamp01(raw);
                    float maskClamped = Mathf.Clamp01(mask);

                    Color heightCol = new Color(rawClamped, rawClamped, rawClamped, 1f);
                    Color maskCol = new Color(maskClamped, maskClamped, maskClamped, 1f);

                    debugHeightTexture.SetPixel(x, y, heightCol);
                    debugMaskTexture.SetPixel(x, y, maskCol);
                }
            }

            debugHeightTexture.Apply();
            debugMaskTexture.Apply();

            Debug.Log("NoiseGenerator: Debug textures generated (Play Mode). Inspect textures on the component.");
        }

        // Public accessors for settings
        public float SeaLevel => seaLevel;
        public float HeightMultiplier => heightMultiplier;
        public int WorldSeed => worldSeed;

        public void SetSeed(int newSeed)
        {
            Initialize(newSeed);
        }

        /// <summary>
        /// Quick test to see if an area contains any terrain worth rendering.
        /// Returns true if any sample point has terrain above the deep water threshold.
        /// </summary>
        public bool HasLandInChunk(Vector2Int chunkCoord, int chunkSize, int sampleResolution = 6)
        {
            float worldOffsetX = chunkCoord.x * chunkSize;
            float worldOffsetZ = chunkCoord.y * chunkSize;

            int res = Mathf.Max(2, sampleResolution);
            float step = (float)chunkSize / (res - 1);
            float deepWaterThreshold = -5f; // Match the threshold in IslandMeshGenerator

            for (int z = 0; z < res; z++)
            {
                for (int x = 0; x < res; x++)
                {
                    float wx = worldOffsetX + x * step;
                    float wz = worldOffsetZ + z * step;
                    // Include chunks with shoreline geometry (slightly underwater)
                    if (GetHeight(wx, wz) > deepWaterThreshold) return true;
                }
            }

            return false;
        }
    }
}
